version: 2.1
orbs:
  upx: circleci/upx@1.0.1
jobs:
  deploy:
    docker:
      - image: circleci/golang:1.14

    steps:
      - checkout

      - restore_cache: # restores saved cache if no changes are detected since last run
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - upx/install

      - run: curl -sL https://git.io/goreleaser | bash -s release --rm-dist -p 3

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

workflows:
  version: 2
  build-workflow:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v?[0-9]+(\.[0-9]+)*(-.*)*/
